name: Staging

on:
  push:
    branches:
      - master

jobs:
  deploy_staging:
    name: Deploy staging
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deployments
        run: |
          sudo mkdir -p /var/www/html  # Ensure directory exists
          sudo rsync -av $GITHUB_WORKSPACE/ azure@172.171.228.11:/var/www/html/
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_SSH_KEY_STAGE }}
