stages:
  - deploy

deploy:
  stage: deploy
  script:
    - cd /home/azure/cvtesting && git pull origin main
    - cp -r /home/azure/cvtesting/. /var/www/html/
    - sudo systemctl reload nginx
  tags:
    - runner1
  only:
    - main

