name: Staging Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy_production:
    name: Deploy to Staging
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: 172.171.228.11
          username: azure
          key: ${{ secrets.PRIVATE_SSH_KEY_STAGE }}
          script: |
            sudo rsync -av $GITHUB_WORKSPACE/ /var/www/html/
