name: Staging

on:
  push:
    branches:
      - master

jobs:
  deploy_staging:
    name: Deploy staging
    runs-on: server2-runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deployments
        run: |
          sudo rsync -av $GITHUB_WORKSPACE/ /var/www/html/
