name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to server
        run: |
          cp -r ${{ github.workspace }}/. /var/www/html/

      - name: Reload Nginx
        run: |
          sudo systemctl reload nginx
