stages:
  - deploy

deploy:
  stage: deploy
  script:
    - cd /home/azure/index && git pull origin main
    - cp -r /home/azure/index/. /var/www/html/
    - sudo systemctl reload nginx
  tags:
    - runner1
  only:
    - main

