stages:
  - deploy

deploy:
  stage: deploy
  script:
    - cd /home/azure/indexx && git pull origin main
    - cp -r /home/azure/indexx/. /var/www/html/
    - sudo systemctl reload nginx
  runs-on: self-hosted
  only:
    - main
