name: Staging

on:
  push:
    branches:
      - master

jobs:
  deploy_staging:
    name: Deploy staging
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deployments
        run: |
          rsync -av $GITHUB_WORKSPACE/ /home/azure/indexx/
